addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - CC=gcc-4.8 GCOV=gcov-4.8

before_install:
  - gcc-4.8 --version
  - gcov-4.8 --version
  - ${CC} --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq parted -y

script: make travis -j $(cat /proc/cpuinfo | grep processor | wc -l)

after_success:
  - pwd && ${GCOV} -v && bash <(curl -s https://codecov.io/bash) -x ${GCOV}
