addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - CC=gcc-4.8 GCOV=gcov-4.8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq parted -y
  - sudo apt-get install -qq lcov -y
  - source setup.sh

script: env CCVERSION=4.8 make -s travis -j $(cat /proc/cpuinfo | grep processor | wc -l)

after_success:
  - make codecov-coverage
  - bash <(curl -s https://codecov.io/bash) -x ${GCOV} -X gcov -X coveragepy
