sudo: required

dist: trusty

before_install:
  - apt-get update -qq
  - apt-get install -qq parted -y
  - apt-get install -qq lcov -y
  - apt-get install -qq cloc -y
  - apt-get install -qq pmccabe -y
  - pip --user install bincopy
  - source setup.sh
  - python --version
  - gcc --version
  - g++ --version
  - ld --version

script: make -s travis -j $(cat /proc/cpuinfo | grep processor | wc -l)

after_success:
  - make codecov-coverage
  - bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
