addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

language: c

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq parted -y

script: make -s travis

after_success:
  - pwd && gcov -v && bash <(curl -s https://codecov.io/bash)
