ignore:
  - "3pp"
  - "examples"
  - "src/boards"
  - "src/drivers/adc.*"
  - "src/drivers/analog_input_pin.*"
  - "src/drivers/analog_output_pin.*"
  - "src/drivers/can.*"
  - "src/drivers/chipid.*"
  - "src/drivers/dac.*"
  - "src/drivers/ds18b20.*"
  - "src/drivers/ds3231.*"
  - "src/drivers/eeprom_i2c.*"
  - "src/drivers/eeprom_soft.*"
  - "src/drivers/esp_wifi"
  - "src/drivers/esp_wifi.*"
  - "src/drivers/exti.*"
  - "src/drivers/flash.*"
  - "src/drivers/i2c.*"
  - "src/drivers/i2c_soft.*"
  - "src/drivers/led_7seg_ht16k33.*"
  - "src/drivers/led_7seg_ht16k33_numbertable.i"
  - "src/drivers/mcp2515.*"
  - "src/drivers/nrf24l01.*"
  - "src/drivers/owi.*"
  - "src/drivers/pin.*"
  - "src/drivers/ports"
  - "src/drivers/pwm.*"
  - "src/drivers/pwm_soft.*"
  - "src/drivers/random.*"
  - "src/drivers/sd.*"
  - "src/drivers/sht3xd.*"
  - "src/drivers/spi.*"
  - "src/drivers/uart.*"
  - "src/drivers/uart_soft.*"
  - "src/drivers/usb"
  - "src/drivers/usb.*"
  - "src/drivers/usb_device.*"
  - "src/drivers/usb_host.*"
  - "src/drivers/watchdog.*"
  - "src/drivers/ws2812.*"
  - "tst"
