ignore:
  - "3pp"
  - "examples"
  - "src/boards"
  - "src/drivers/adc.c"
  - "src/drivers/analog_input_pin.c"
  - "src/drivers/analog_output_pin.c"
  - "src/drivers/can.c"
  - "src/drivers/chipid.c"
  - "src/drivers/dac.c"
  - "src/drivers/ds18b20.c"
  - "src/drivers/ds3231.c"
  - "src/drivers/eeprom_i2c.c"
  - "src/drivers/eeprom_soft.c"
  - "src/drivers/esp_wifi"
  - "src/drivers/esp_wifi.c"
  - "src/drivers/exti.c"
  - "src/drivers/flash.c"
  - "src/drivers/i2c.c"
  - "src/drivers/i2c_soft.c"
  - "src/drivers/led_7seg_ht16k33.c"
  - "src/drivers/led_7seg_ht16k33_numbertable.i"
  - "src/drivers/mcp2515.c"
  - "src/drivers/nrf24l01.c"
  - "src/drivers/owi.c"
  - "src/drivers/pin.c"
  - "src/drivers/ports"
  - "src/drivers/pwm.c"
  - "src/drivers/pwm_soft.c"
  - "src/drivers/random.c"
  - "src/drivers/sd.c"
  - "src/drivers/sht3xd.c"
  - "src/drivers/spi.c"
  - "src/drivers/uart.c"
  - "src/drivers/uart_soft.c"
  - "src/drivers/usb"
  - "src/drivers/usb.c"
  - "src/drivers/usb_device.c"
  - "src/drivers/usb_host.c"
  - "src/drivers/watchdog.c"
  - "src/drivers/ws2812.c"
  - "tst"
