ignore:
  - "3pp"
  - "examples"
  - "src/boards"
  - "src/drivers/basic/adc.*"
  - "src/drivers/basic/analog_input_pin.*"
  - "src/drivers/basic/analog_output_pin.*"
  - "src/drivers/network/can.*"
  - "src/drivers/basic/chipid.*"
  - "src/drivers/basic/dac.*"
  - "src/drivers/sensors/ds18b20.*"
  - "src/drivers/various/ds3231.*"
  - "src/drivers/storage/eeprom_i2c.*"
  - "src/drivers/storage/eeprom_soft.*"
  - "src/drivers/network/esp_wifi"
  - "src/drivers/network/esp_wifi.*"
  - "src/drivers/basic/exti.*"
  - "src/drivers/storage/flash.*"
  - "src/drivers/network/i2c.*"
  - "src/drivers/network/i2c_soft.*"
  - "src/drivers/displays/led_7seg_ht16k33.*"
  - "src/drivers/displays/led_7seg_ht16k33_numbertable.i"
  - "src/drivers/network/mcp2515.*"
  - "src/drivers/network/nrf24l01.*"
  - "src/drivers/network/owi.*"
  - "src/drivers/basic/pin.*"
  - "src/drivers/ports"
  - "src/drivers/basic/pwm.*"
  - "src/drivers/basic/pwm_soft.*"
  - "src/drivers/basic/random.*"
  - "src/drivers/storage/sd.*"
  - "src/drivers/sensors/sht3xd.*"
  - "src/drivers/network/spi.*"
  - "src/drivers/network/uart.*"
  - "src/drivers/network/uart_soft.*"
  - "src/drivers/network/usb"
  - "src/drivers/network/usb.*"
  - "src/drivers/network/usb_device.*"
  - "src/drivers/network/usb_host.*"
  - "src/drivers/basic/watchdog.*"
  - "src/drivers/displays/ws2812.*"
  - "tst"
