name: All

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Test
      run: |
        source setup.sh
        make -j $(nproc) test CDEFS_EXTRA="CONFIG_ASSERT=1"
